### ISSUE TITLE
SonarQube not running on Apple Silicon (M1/M2)

### ISSUE THREAD

**Issue by luisaveiro** [luisaveiro/localhost-sonarqube#9]
#### Description
When running the `sonarqube up` command, users are getting the following error:

```bash
Pulling sonarqube (sonarqube:latest)...
latest: Pulling from library/sonarqube
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

#### Expected Behaviour
SonarQube should start.

#### Current Behaviour
Localhost SonarQube is unable to start the SonarQube dashboard.

#### Possible Solution
MySQL Docker image supports the `platform` service configuration option.

```yml
services:
  mysql:
    image: mysql:latest
    # Enable platform for Apple Silicon.
    platform: linux/x86_64
```

#### Steps to Reproduce

1. Run `sonarqube up`

#### Screenshots
<img width="1145" alt="Screenshot 2023-01-24 at 17 36 12" src="https://user-images.githubusercontent.com/758559/214376121-96dd8630-ecc4-45fc-b216-61cb5519ee2f.png">

#### Additional Context
You need a Mac with Apple Silicon. Mac with Intel chips are not affected by this issue.

#### Your Environment

* Localhost SonarQube version used: 1.0.4
* Operating System and version: MacOS

**Comment by luisaveiro** [comment]
I found this [discussion](https://community.sonarsource.com/t/apple-silicon-support-sonarqube-and-sonarscanner/55094/14) on the SonarSource community forum that suggests using a `8.9.2-community` tag for SonarQube Docker image.

```yml
sonarqube:
    image: sonarqube:8.9.2-community
    platform: linux/amd64
```
